name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BACKSTAGE_UPLOAD_SECRET: ${{ secrets.BACKSTAGE_UPLOAD_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
      HIRPINIA_DRIVE_FOLDER_ID: ${{ secrets.HIRPINIA_DRIVE_FOLDER_ID }}
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v6
      - name: Tests with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run lint && npm run prettier-check
      - run: npm run build
